name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: zig build
      - run: zig build test
      - run: zig build testnet
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: zig fmt --check .
